### 실행 단축키 : shift + enter

In [2]:
!pip install numpy

In [3]:
import numpy as np
a = np.array([0,1,2,3]) #list 를 컨테이너로 담을 수 있다
print(a)

print(np.arange(10))  # a를 붙여서 range 라고 쓴다

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [7]:
L = range(1000)
%timeit [i**2 for i in L] #cpu time을 계산할때 사용 실행시간 볼 수 있다 49.5ms

49.5 µs ± 2.15 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [60]:
a = np.arange(1000)
%timeit a**2 # 100만번에 1.75ms < 만번에 49,5ms 

1.75 µs ± 263 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


##### Why it is useful : Memory-efficient container that provides fast numerical operation (numpy 는 빠른 하드웨어 연산을 도와준다)

## 1차원 배열 만들기

In [10]:
# 0
# 1
# 2
# 3
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [11]:
#a의 차원보기
a.ndim

1

In [12]:
#a의 모양보기
a.shape

(4,)

In [13]:
len(a) #행의 수

4

## 2차원 배열 만들기 

In [15]:
# 0 1 2
# 3 4 5

b = np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
b.ndim

2

In [18]:
b.shape

(2, 3)

In [19]:
len(b) #첫번째 차원 (행의 수)

2

## 3차원 배열 만들기 

In [20]:
c = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [22]:
c.ndim

3

In [23]:
c.shape #2row 2col 2depth

(2, 2, 2)

## array를 함수로 만들기

In [24]:
a = np.arange(10) #aragne
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
b = np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [26]:
a = np.linspace(0,1,6) #start , end, points 구간을 개수만큼 나누기
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [27]:
a = np.ones((3,3)) #3,3 크기의 1로 구성된 배열
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
a = np.zeros((3,3)) #3,3 크기의 0로 구성된 배열
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
c = np.eye(3) #eye 단위행렬 정방행렬 대각선의 원소의 개수가 3

c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
d = np.eye(3,2) #3은 행 2는 열 
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [31]:
a = np.diag([1,2,3,4]) #대각원소가 1,2,3,4
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [32]:
np.diag(a) #대각원소의 값만 추출 

array([1, 2, 3, 4])

In [33]:
a = np.random.rand(4) #0~1사이 (0은 나오고 1은 안나옴) 4개의 원소를 갖는 배열
a

array([0.67991545, 0.65106143, 0.56518257, 0.12630159])

In [34]:
a = np.random.randn(4) #표준정규분표에서 생성 (가우시안)
a

array([ 0.2072526 ,  0.44080423,  0.82578612, -1.25680996])

표준정규분포<br>
N(0,1) <br>
N(mu,sigma) 

## Basic data type - int32, float64

In [35]:
a = np.arange(10)
a.dtype

dtype('int32')

In [36]:
a = np.arange(10,dtype='float64') #datatype을 float으로 설정하기 -> 소수점으로 바뀜
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [37]:
a = np.zeros((3,3)) #기본 datatype이 float64이다
a.dtype

dtype('float64')

## other datatype - complex, boolean

In [38]:
d = np.array([1+2j,2+4j]) #complex
d.dtype

dtype('complex128')

In [40]:
d = np.array([True,False])
d.dtype

dtype('bool')

In [41]:
a = np.array(['Ran',"Robert"])
a.dtype #U = Unicode 

dtype('<U6')

## Indexing and Slicing

#### Indexing

In [42]:
a = np.arange(10)
print(a[5])

5


In [43]:
a #list형태는 아닙니다. array입니다.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a= np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [45]:
a[2,2] #index값은 0부터 시작합니다

3

In [47]:
a[2,1] = 5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

#### Slicing

In [48]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a[1:8:2]

array([1, 3, 5, 7])

In [50]:
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [51]:
b = np.arange(5)
a = b[::-1]
a

array([4, 3, 2, 1, 0])

## Copies and Views

#### 새로운 기억장소에 할당되는것이 아니다

In [52]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [54]:
np.shares_memory(a,b) #a와 b는 메모리를 공유하고있느냐? True

True

In [55]:
b[0]=10
b

array([10,  2,  4,  6,  8])

In [56]:
a #b를 바꾸니 a도 갱신이 된다 (두개가 메모리를 공유하고있었기때문에)

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [57]:
a=np.arange(10)
c=a[::2].copy() #.copy() 를 쓰면 메모리를 share하지 않는다
c

array([0, 2, 4, 6, 8])

In [58]:
np.shares_memory(a,c)

False

## Fancy Indexing

In [61]:
a = np.random.randint(0,20,15)
a

array([11, 11, 10, 19,  3,  3, 12,  8, 17,  7, 13,  3, 18, 15,  2])

In [62]:
mask = (a%2 ==0) #짝수를 만나면 True 홀수는 False
mask

array([False, False,  True, False, False, False,  True,  True, False,
       False, False, False,  True, False,  True])

In [63]:
mask = (a%3==0)
mask

array([False, False, False, False,  True,  True,  True, False, False,
       False, False,  True,  True,  True, False])

In [64]:
a[mask] = -1
a

array([11, 11, 10, 19, -1, -1, -1,  8, 17,  7, 13, -1, -1, -1,  2])

#### Indexing with an array of integers

In [66]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [67]:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [68]:
a[[9,7]]= -200
a


array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

## Numerical Operation in Numpy

In [4]:
a = np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [5]:
a**2

array([ 1,  4,  9, 16])

In [6]:
b = np.ones(4)+1
a-b

array([-1.,  0.,  1.,  2.])

In [9]:
a*b

array([2., 4., 6., 8.])

In [8]:
b

array([2., 2., 2., 2.])

In [11]:
c = np.diag([1,2,3,4])
print(c*c)
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [13]:
#비교연산
a==b

array([False,  True, False, False])

In [14]:
a>b

array([False, False,  True,  True])

In [15]:
np.array_equal(a,b)

False

In [16]:
a=np.array([1,0,1,0],dtype=bool)
b=np.array([1,0,1,0],dtype=bool)
np.logical_or(a,b)

array([ True, False,  True, False])

In [17]:
a = np.arange(40)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
       -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388,
       -0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
       -0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539])

In [18]:
np.log(a)

C:\Users\goeun\AppData\Local\Temp\ipykernel_3076\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583,
       3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
       3.55534806, 3.58351894, 3.61091791, 3.63758616, 3.66356165])

In [19]:
np.exp(a) #e의 n승

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
       1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
       7.89629602e+13, 2.14643580e+14, 5.83461743e+14, 1.58601345e+15,
       4.31123155e+15, 1.17191424e+16, 3.18559318e+16, 8.65934004e+16])

shape가 다르면 valueError

## Basic Reductions

In [21]:
x = np.array([1,2,3,4])
np.sum(x)

10

In [24]:
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [25]:
x.sum(axis=0) #열을 더함

array([3, 3])

In [26]:
x.sum(axis=1)#행을 더함

array([2, 4])

## Other reductions

In [27]:
x = np.array([1,3,2])
x.min()

1

In [28]:
x.max() #index값 반환

3

In [30]:
x.argmin() #index of minimum element

0

In [31]:
x.argmax() #index of maximum element

1

## Logical Operations

In [33]:
np.all([True,True,False]) #all is true = true

False

In [34]:
np.any([True,False,False]) #least one is true = true

True

In [35]:
a=np.zeros((50,50))
np.any(a!=0) #하나라도 0이 아닌것이 있냐

False

In [36]:
np.all(a==a) #all elements are equal

True

In [37]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])
((a<=b)&(b<=c)).all()

True

In [38]:
x = np.array([1,2,3,1])
y=np.array([[1,2,3],[5,6,1]])
x.mean() #average

1.75

In [39]:
y.mean()

3.0

In [40]:
np.median(x) #중앙값

1.5

In [41]:
np.median(y,axis=-1)#last axis 

array([2., 5.])

In [42]:
y

array([[1, 2, 3],
       [5, 6, 1]])

In [43]:
x.std() #표준편차

0.82915619758885

In [44]:
y.std()

1.9148542155126762